# Generated by Django 3.2.16 on 2022-10-31 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('media_url', models.CharField(max_length=512, unique=True, verbose_name='URL of the media asset')),
                ('media_file_data_id', models.IntegerField(verbose_name='ID provided by Battle.net endpoints')),
                ('profession_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='profession ID')),
                ('is_primary', models.BooleanField(verbose_name='TRUE if the profession is a primary profession')),
            ],
            options={
                'db_table': 'professions',
            },
        ),
        migrations.CreateModel(
            name='ProfessionSkillTiers',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('skill_tier_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='skill tier ID')),
                ('is_primary', models.BooleanField(verbose_name='TRUE if the profession is a primary profession')),
                ('min_skill_level', models.SmallIntegerField(verbose_name='minimum skill level (eg. 301 for Burning Crusade)')),
                ('max_skill_level', models.SmallIntegerField(verbose_name='maximum skill level (eg. 375 for Burning Crusade)')),
                ('profession_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfl.professions')),
            ],
            options={
                'db_table': 'profession_skill_tiers',
            },
        ),
    ]
