# Generated by Django 3.2.16 on 2022-10-31 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionskilltiers',
            name='is_primary',
        ),
        migrations.AlterField(
            model_name='professions',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='TRUE if the profession is a primary profession'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='media_file_data_id',
            field=models.IntegerField(null=True, verbose_name='ID provided by Battle.net endpoints'),
        ),
        migrations.AlterField(
            model_name='professionskilltiers',
            name='profession_id',
            field=models.ForeignKey(db_column='profession_id', on_delete=django.db.models.deletion.CASCADE, to='wfl.professions'),
        ),
    ]
