# Generated by Django 3.2.16 on 2022-10-31 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0002_auto_20221031_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professions',
            new_name='Profession',
        ),
        migrations.RenameModel(
            old_name='ProfessionSkillTiers',
            new_name='ProfessionSkillTier',
        ),
        migrations.AlterModelTable(
            name='profession',
            table='profession',
        ),
        migrations.AlterModelTable(
            name='professionskilltier',
            table='profession_skill_tier',
        ),
    ]
