# Generated by Django 3.2.16 on 2022-11-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0004_auto_20221101_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionskilltier',
            name='is_legacy_tier',
            field=models.BooleanField(default=False, verbose_name='TRUE if the tier requires previous tiers to unlock'),
        ),
    ]
