# Generated by Django 3.2.16 on 2022-11-02 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0005_professionskilltier_is_legacy_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionskilltier',
            name='profession_id',
        ),
        migrations.AddField(
            model_name='professionskilltier',
            name='profession',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wfl.profession'),
            preserve_default=False,
        ),
    ]
