# Generated by Django 3.2.16 on 2022-11-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0006_auto_20221102_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgRecipeItem',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('stg_recipe_item_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='concatenation of IDs for recipe / item / crafted_item')),
                ('recipe_id', models.IntegerField(default=0, verbose_name='recipe ID')),
                ('item_id', models.IntegerField(default=0, verbose_name='reagent item ID')),
                ('crafted_item_id', models.IntegerField(default=0, verbose_name='crafted item ID')),
            ],
            options={
                'db_table': 'stg_recipe_item',
            },
        ),
    ]
