# Generated by Django 3.2.16 on 2022-11-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0007_stgrecipeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgrecipeitem',
            name='stg_recipe_item_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='concatenation of IDs for recipe / item / crafted_item'),
        ),
    ]
