# Generated by Django 3.2.16 on 2022-11-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0008_alter_stgrecipeitem_stg_recipe_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgrecipeitem',
            name='stg_recipe_item_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='dummy primary key field'),
        ),
    ]
