# Generated by Django 3.2.16 on 2022-11-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0009_alter_stgrecipeitem_stg_recipe_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='is_crafting',
            field=models.BooleanField(default=False, verbose_name='TRUE if the profession crafts items'),
        ),
    ]
