# Generated by Django 3.2.16 on 2022-11-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0010_profession_is_crafting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgrecipeitem',
            name='stg_recipe_item_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='concat (recipe / reagent item / crafted item IDs) as dummy PK'),
        ),
    ]
