# Generated by Django 3.2.16 on 2022-11-04 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0012_itemclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSubclass',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('item_subclass_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='item subclass ID')),
                ('item_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfl.itemclass')),
            ],
            options={
                'db_table': 'item_subclass',
            },
        ),
    ]
