# Generated by Django 3.2.16 on 2022-11-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0015_auto_20221104_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemclasshierarchy',
            name='item_class_hierarchy_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='unique identifier for item_class and item_subclass IDs'),
        ),
    ]
