# Generated by Django 3.2.16 on 2022-11-07 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0016_alter_itemclasshierarchy_item_class_hierarchy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('item_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='item ID')),
                ('purchase_price', models.IntegerField(default=0, verbose_name='item vendor purchase price')),
                ('sell_price', models.IntegerField(default=0, verbose_name='item vendor sell price')),
                ('game_version', models.CharField(choices=[('CLASSIC', 'CLASSIC'), ('RETAIL', 'RETAIL')], default='RETAIL', max_length=256, verbose_name='game version of the item')),
                ('level', models.SmallIntegerField(default=0, verbose_name='item level')),
                ('required_level', models.SmallIntegerField(default=0, verbose_name='required player level')),
                ('quality', models.CharField(choices=[('POOR', 'POOR'), ('COMMON', 'COMMON'), ('UNCOMMON', 'UNCOMMON'), ('RARE', 'RARE'), ('EPIC', 'EPIC'), ('LEGENDARY', 'LEGENDARY'), ('HEIRLOOM', 'HEIRLOOM')], default='COMMON', max_length=256, verbose_name='quality level')),
                ('item_class_hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfl.itemclasshierarchy')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
