# Generated by Django 3.2.16 on 2022-11-08 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0018_auto_20221107_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('media_url', models.CharField(max_length=512, null=True, unique=True, verbose_name='URL of the media asset')),
                ('media_file_data_id', models.IntegerField(null=True, verbose_name='ID provided by Battle.net endpoints')),
                ('item_data_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='unique identifier for item_id and game_version')),
                ('purchase_price', models.IntegerField(default=0, verbose_name='item vendor purchase price')),
                ('sell_price', models.IntegerField(default=0, verbose_name='item vendor sell price')),
                ('game_version', models.CharField(choices=[('CLASSIC', 'CLASSIC'), ('RETAIL', 'RETAIL')], default='RETAIL', max_length=256, verbose_name='game version of the item')),
                ('level', models.SmallIntegerField(default=0, verbose_name='item level')),
                ('required_level', models.SmallIntegerField(default=0, verbose_name='required player level')),
                ('quality', models.CharField(choices=[('POOR', 'POOR'), ('COMMON', 'COMMON'), ('UNCOMMON', 'UNCOMMON'), ('RARE', 'RARE'), ('EPIC', 'EPIC'), ('LEGENDARY', 'LEGENDARY'), ('HEIRLOOM', 'HEIRLOOM')], default='COMMON', max_length=256, verbose_name='quality level')),
            ],
            options={
                'db_table': 'item_data',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='game_version',
        ),
        migrations.RemoveField(
            model_name='item',
            name='level',
        ),
        migrations.RemoveField(
            model_name='item',
            name='media_file_data_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='item',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='item',
            name='required_level',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='item',
            name='classic_item_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classic_item_data', to='wfl.itemdata'),
        ),
        migrations.AddField(
            model_name='item',
            name='retail_item_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_item_data', to='wfl.itemdata'),
        ),
    ]
