# Generated by Django 3.2.16 on 2022-11-08 18:04

from django.db import migrations, models
import wfl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0019_auto_20221108_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='game_version',
            field=models.CharField(choices=[('CLASSIC', 'CLASSIC'), ('RETAIL', 'RETAIL')], default=wfl.utils.GameVersion['RETAIL'], max_length=256, verbose_name='game version of the item'),
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='quality',
            field=models.CharField(choices=[('POOR', 'POOR'), ('COMMON', 'COMMON'), ('UNCOMMON', 'UNCOMMON'), ('RARE', 'RARE'), ('EPIC', 'EPIC'), ('LEGENDARY', 'LEGENDARY'), ('HEIRLOOM', 'HEIRLOOM')], default=wfl.utils.ItemQuality['COMMON'], max_length=256, verbose_name='quality level'),
        ),
    ]
