# Generated by Django 3.2.16 on 2022-11-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0020_auto_20221108_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='media_url',
            field=models.CharField(max_length=512, null=True, verbose_name='URL of the media asset'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='media_url',
            field=models.CharField(max_length=512, null=True, verbose_name='URL of the media asset'),
        ),
    ]
