# Generated by Django 3.2.16 on 2022-11-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0021_auto_20221108_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('expansion_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='expansion ID')),
                ('short_name', models.CharField(default='', max_length=256, verbose_name='short name of the expansion')),
                ('max_level', models.SmallIntegerField(default=0, verbose_name='max character level')),
                ('is_classic', models.BooleanField(default=False, verbose_name='TRUE if this expansion is part of Classic')),
            ],
            options={
                'db_table': 'expansion',
            },
        ),
    ]
