# Generated by Django 3.2.16 on 2022-11-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0022_expansion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expansion',
            name='short_name',
        ),
        migrations.AddField(
            model_name='expansion',
            name='skill_tier_prefix',
            field=models.CharField(default='', max_length=256, verbose_name='prefix to identy the expansion skill tiers'),
        ),
    ]
