# Generated by Django 3.2.16 on 2022-11-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0024_professionskilltier_expansion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('media_url', models.CharField(max_length=512, null=True, verbose_name='URL of the media asset')),
                ('media_file_data_id', models.IntegerField(null=True, verbose_name='ID provided by Battle.net endpoints')),
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='recipe ID')),
                ('min_quantity', models.SmallIntegerField(default=1, verbose_name='min quantity produced')),
                ('max_quantity', models.SmallIntegerField(default=1, verbose_name='max quantity produced')),
                ('crafted_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfl.item')),
                ('skill_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfl.professionskilltier')),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
    ]
