# Generated by Django 3.2.16 on 2022-11-11 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0025_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('reagent_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='concat (recipe / item IDs) as dummy PK')),
                ('item_quantity', models.SmallIntegerField(default=1, verbose_name='quantity required')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfl.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfl.recipe')),
            ],
            options={
                'db_table': 'reagent',
            },
        ),
    ]
