# Generated by Django 3.2.16 on 2022-11-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0026_reagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgrecipeitem',
            name='skill_tier_id',
            field=models.IntegerField(default=0, verbose_name='skill tier ID'),
        ),
    ]
