# Generated by Django 3.2.16 on 2022-11-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0027_stgrecipeitem_skill_tier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgrecipeitem',
            name='item_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='reagent item quantity'),
        ),
    ]
