# Generated by Django 3.2.16 on 2022-11-14 23:53

from django.db import migrations, models
import wfl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0028_stgrecipeitem_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('region_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='region ID')),
                ('tag', models.CharField(default='', max_length=256, verbose_name='region tag')),
                ('game_version', models.CharField(choices=[('CLASSIC', 'CLASSIC'), ('RETAIL', 'RETAIL')], default=wfl.utils.GameVersion['RETAIL'], max_length=256, verbose_name='game version of the region')),
            ],
            options={
                'db_table': 'region',
            },
        ),
    ]
