# Generated by Django 3.2.16 on 2022-11-15 04:20

from django.db import migrations, models
import django.db.models.deletion
import wfl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0029_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('realm_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='realm ID')),
                ('slug', models.CharField(default='', max_length=256, verbose_name='realm slug')),
                ('realm_type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('PVP', 'PVP'), ('PVP_RP', 'PVP_RP'), ('RP', 'RP')], default=wfl.utils.RealmType['NORMAL'], max_length=256, verbose_name='NORMAL / PVP / PVP_RP / RP')),
                ('realm_category', models.CharField(choices=[('BRAZIL', 'BRAZIL'), ('LATIN_AMERICA', 'LATIN_AMERICA'), ('OCEANIC', 'OCEANIC'), ('UNITED_STATES', 'UNITED_STATES'), ('US_EAST', 'US_EAST'), ('US_WEST', 'US_WEST')], default=wfl.utils.RealmCategory['UNITED_STATES'], max_length=256, verbose_name='geographic region')),
                ('timezone', models.CharField(default='', max_length=256, verbose_name='realm timezone / locale')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfl.region')),
            ],
            options={
                'db_table': 'realm',
            },
        ),
    ]
