# Generated by Django 3.2.16 on 2022-11-16 03:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wfl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0034_alter_connectedrealm_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionHouse',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('auction_house_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='concat connected_realm_id and faction_id as dummy PK')),
                ('faction', models.CharField(choices=[('ALLIANCE', 'ALLIANCE'), ('HORDE', 'HORDE'), ('BLACKWATER', 'BLACKWATER')], default=wfl.utils.Faction['ALLIANCE'], max_length=256, verbose_name='Alliance / Horde / Blackwater')),
                ('faction_id', models.SmallIntegerField(choices=[(2, 'ALLIANCE'), (6, 'HORDE'), (7, 'BLACKWATER')], default=wfl.utils.AuctionHouseFaction['ALLIANCE'], verbose_name='auction house faction ID')),
                ('connected_realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfl.connectedrealm')),
            ],
            options={
                'db_table': 'auction_house',
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('auction_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='auction ID')),
                ('item_id', models.IntegerField(default=0, verbose_name='item ID of the auctioned item')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='quantity of auction item')),
                ('bid_unit_price', models.IntegerField(default=1, verbose_name='bid price per auction item')),
                ('buyout_unit_price', models.IntegerField(null=True, verbose_name='buyout price per auction item')),
                ('time_left', models.CharField(choices=[('SHORT', 'SHORT'), ('MEDIUM', 'MEDIUM'), ('LONG', 'LONG'), ('VERY_LONG', 'VERY_LONG')], default=wfl.utils.AuctionTimeLeft['LONG'], max_length=256, verbose_name='SHORT / MEDIUM / LONG / VERY_LONG')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime the auction was loaded')),
                ('update_date', models.DateField(default=datetime.date.today, verbose_name='date the auction was loaded')),
                ('auction_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfl.auctionhouse')),
            ],
            options={
                'db_table': 'auction',
            },
        ),
    ]
