# Generated by Django 3.2.16 on 2022-11-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0035_auction_auctionhouse'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['auction_house', 'update_date'], name='auction_auction_f0e4ad_idx'),
        ),
    ]
