# Generated by Django 3.2.16 on 2022-11-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0036_auction_auction_auction_f0e4ad_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_unit_price',
            field=models.IntegerField(null=True, verbose_name='bid price per auction item'),
        ),
    ]
