# Generated by Django 3.2.16 on 2023-01-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0038_itemdata_is_vendor_item'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['update_date', 'update_time'], name='auction_update__9dee67_idx'),
        ),
    ]
