# Generated by Django 3.2.16 on 2023-01-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0041_auto_20230113_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionsummary',
            name='min_quantity',
            field=models.IntegerField(default=1, verbose_name='quantity of auction item at the min_price'),
        ),
        migrations.AlterField(
            model_name='auctionsummary',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='quantity of auction item'),
        ),
    ]
