# Generated by Django 3.2.16 on 2023-01-15 03:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wfl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0043_auto_20230115_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('auction_listing_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='concat date / hour / auction_id as dummy PK')),
                ('auction_id', models.IntegerField(default=0, verbose_name='auction ID')),
                ('item_id', models.IntegerField(default=0, verbose_name='item ID of the auctioned item')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='quantity of auction item')),
                ('bid_unit_price', models.IntegerField(null=True, verbose_name='bid price per auction item')),
                ('buyout_unit_price', models.IntegerField(null=True, verbose_name='buyout price per auction item')),
                ('time_left', models.CharField(choices=[('SHORT', 'SHORT'), ('MEDIUM', 'MEDIUM'), ('LONG', 'LONG'), ('VERY_LONG', 'VERY_LONG')], default=wfl.utils.AuctionTimeLeft['LONG'], max_length=256, verbose_name='SHORT / MEDIUM / LONG / VERY_LONG')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime the auction was loaded')),
                ('update_date', models.DateField(default=datetime.date.today, verbose_name='date the auction was loaded')),
                ('update_hour', models.IntegerField(default=0, verbose_name='hour bucket the auction was loaded')),
                ('auction_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfl.auctionhouse')),
            ],
            options={
                'db_table': 'auction',
            },
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['auction_house', 'update_date'], name='auction_auction_f0e4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['update_date', 'update_hour'], name='auction_update__c696d1_idx'),
        ),
    ]
