# Generated by Django 3.2.16 on 2023-01-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0044_auto_20230115_0356'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auctionsummary',
            name='auction_sum_auction_08883f_idx',
        ),
        migrations.AddIndex(
            model_name='auctionsummary',
            index=models.Index(fields=['auction_house', 'update_date', 'update_hour', 'item_id'], name='auction_sum_auction_6189bd_idx'),
        ),
    ]
