# Generated by Django 3.2.16 on 2023-02-27 21:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0045_auto_20230123_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSummaryLatest',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='object name')),
                ('auction_summary_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='concat auction house / item / date / hour as dummy PK')),
                ('item_id', models.IntegerField(default=0, verbose_name='item ID of the auctioned item')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity of auction item')),
                ('vwap', models.IntegerField(null=True, verbose_name='VWAP per auction item')),
                ('min_quantity', models.IntegerField(default=1, verbose_name='quantity of auction item at the min_price')),
                ('min_price', models.IntegerField(null=True, verbose_name='buyout price per auction item')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime the auction summary was loaded')),
                ('update_date', models.DateField(default=datetime.date.today, verbose_name='date the auction summary was loaded')),
                ('update_hour', models.IntegerField(default=0, verbose_name='hour bucket the auction summary was loaded')),
                ('auction_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfl.auctionhouse')),
            ],
            options={
                'db_table': 'auction_summary_latest',
            },
        ),
        migrations.AddIndex(
            model_name='auctionsummarylatest',
            index=models.Index(fields=['auction_house', 'item_id'], name='auction_sum_auction_bec346_idx'),
        ),
    ]
