# Generated by Django 3.2.16 on 2023-12-01 19:19

from django.db import migrations, models
import wfl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wfl', '0046_auto_20230227_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='game_version',
            field=models.CharField(choices=[('CLASSIC', 'CLASSIC'), ('ERA', 'ERA'), ('RETAIL', 'RETAIL')], default=wfl.utils.GameVersion['RETAIL'], max_length=256, verbose_name='game version of the item'),
        ),
        migrations.AlterField(
            model_name='realm',
            name='realm_category',
            field=models.CharField(choices=[('BRAZIL', 'BRAZIL'), ('CLASSIC', 'CLASSIC'), ('HARDCORE', 'HARDCORE'), ('LATIN_AMERICA', 'LATIN_AMERICA'), ('OCEANIC', 'OCEANIC'), ('SEASONAL', 'SEASONAL'), ('UNITED_STATES', 'UNITED_STATES'), ('US_EAST', 'US_EAST'), ('US_WEST', 'US_WEST')], default=wfl.utils.RealmCategory['UNITED_STATES'], max_length=256, verbose_name='geographic region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='game_version',
            field=models.CharField(choices=[('CLASSIC', 'CLASSIC'), ('ERA', 'ERA'), ('RETAIL', 'RETAIL')], default=wfl.utils.GameVersion['RETAIL'], max_length=256, verbose_name='game version of the region'),
        ),
    ]
